### PR TITLE
Dont merge this PR - offtopic  possible issue with bot in general

### PR DESCRIPTION
**Pull request by koderian**
Can you host this bot somewhere else other then GitHub? or else it's guaranteed to get taken down by Microsoft in the coming days... host it on Notabug, telegram, etc

### CODE REVIEW

**Comment by koderian** [comment]
@tmxkn1

**Comment by AnthonyZJiang** [comment]
Is there an action by ms or what?

**Comment by koderian** [comment]
Yes, MSFT will most likely take your repo down. They have done it before with other bots. That's why I suggesr hosting the bot repository on a different platform, such as

- Notabug.org
- Telegram
- Discord?

**Comment by koderian** [comment]
Can you host this somewhere else just in case?
@tmxkn1

**Comment by AnthonyZJiang** [comment]
> Can you host this somewhere else just in case?
> @tmxkn1


Sorry was super busy with work.
[here](https://gitlab.com/tmxkn1/Microsoft-Rewards-Bot)

**Pull request closed without merging**
